name: lint

on:
  push:
    branches: [main, devel]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: greenbone/actions/lint-python@v3
        with:
          python-version: '3.11'
          package-manager: uv
          cache: 'true'
          cache-dependency-path: uv.lock
          packages: src tests
          formatter: ruff format --check
          linter: ruff check
