name: lint

on:
  push:
    branches: [main, devel]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: greenbone/actions/lint-python@main
        with:
          python-version: '3.11'
          install-args: --group dev
          ruff-check-args: .
          ruff-format-args: --check .
